### ISSUE TITLE
10000 - непонятное число

### ISSUE THREAD

**Issue by coursar** [AlbertKhayrullin/BMI-Deposit#1]
https://github.com/AlbertKhayrullin/BMI-Deposit/blob/8b1ab73cec9874c2eb7d73ec2452d0b932ff1bf5/src/BMI.java#L5

**Comment by AlbertKhayrullin** [comment]
К сожалению не получилось внести исправления в данный репозиторий, поэтому для данного проекта создан новый с исправлением указанных замечаний BMIcorrect/src/BMI.java
